[project]
name = "makra-workspace"
version = "0.1.0"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    # don't want to download torch now
	# "marcus",
	"moleman",
	"morpheus",
	"makra-telemetry",
    # i think this sub dependency of others so it should be handled there not here
	# "makra-shared",
	"makra",
]

[tool.uv.sources]
# marcus = { workspace = true }
moleman = { workspace = true }
morpheus = { workspace = true }
makra-telemetry = { workspace = true }
# makra-shared = { workspace = true }
makra = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/marcus",
    "packages/moleman",
    "packages/morpheus",
    "packages/telemetry",
    "packages/shared",
    "packages/sdk/python",
]
